// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6QdoFu_DwOgoZ7Wf9kPM3oSrriGFGGjA',
    appId: '1:261212268544:web:ff57dccb00dd478285d0e5',
    messagingSenderId: '261212268544',
    projectId: 'child-health-tracker-7aad1',
    authDomain: 'child-health-tracker-7aad1.firebaseapp.com',
    storageBucket: 'child-health-tracker-7aad1.firebasestorage.app',
    measurementId: 'G-DRH8KKCWDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvQ4dHbGhUPmlqQFi1zsJHgU51K0R7HIQ',
    appId: '1:261212268544:android:a06df551afdafee685d0e5',
    messagingSenderId: '261212268544',
    projectId: 'child-health-tracker-7aad1',
    storageBucket: 'child-health-tracker-7aad1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlfx2ql4wZVJjlwSFWeuL9ccqya8kpIvo',
    appId: '1:261212268544:ios:3d00b76af928e39185d0e5',
    messagingSenderId: '261212268544',
    projectId: 'child-health-tracker-7aad1',
    storageBucket: 'child-health-tracker-7aad1.firebasestorage.app',
    iosBundleId: 'com.nickoiv.childhealth',
  );
}
