import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb;

/// Firebase configuration for project `child-health-tracker-7aad1`.
///
/// Written by hand from the console rather than generated by
/// `flutterfire configure`, because the CLI needs an interactive Google login.
/// Regenerating it later with the CLI is safe and will simply overwrite this.
///
/// These values are not secrets: every Firebase web app ships them inside its
/// JavaScript bundle. Access control comes from the Firestore security rules in
/// `firestore.rules`, not from keeping the key hidden.
class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    throw UnsupportedError(
      'Firebase is configured for the web target only. Register an app for '
      '$defaultTargetPlatform in the Firebase console and add its options '
      'here, or run `flutterfire configure` to regenerate this file.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6QdoFu_DwOgoZ7Wf9kPM3oSrriGFGGjA',
    authDomain: 'child-health-tracker-7aad1.firebaseapp.com',
    projectId: 'child-health-tracker-7aad1',
    storageBucket: 'child-health-tracker-7aad1.firebasestorage.app',
    messagingSenderId: '261212268544',
    appId: '1:261212268544:web:ff57dccb00dd478285d0e5',
    measurementId: 'G-DRH8KKCWDB',
  );
}
